config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  resources :topics
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :topics, through: :meetups
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  belongs_to :topic
  belongs_to :event
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :events, through: :meetups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @meetup = Meetup.where(event_id: @event)[0]
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @meetups = Meetup.where(topic_id: @topic)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<% @events.each do |event| %>
  <%= link_to event.name, event_path(event) %><br>
  <%= event.location %><br>
  <%= event.date %><br>
  <br>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<h4>
  Topic: <%= link_to @meetup.topic.name, topic_path(@meetup.topic) %><br>
  Location: <%= @event.location %><br>
  Date: <%= @event.date %>
</h4>

<p><%= @event.description %></p>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div data-alert class="alert-box <%= type %>">
    <%= message %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetups In Space - Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="top-bar">
      <div class="container">
        <a class="logo" href="/">Meetups in Space</a>

        <ul class="top-bar-section">
          <%= render "layouts/flash" %>
        </ul>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/topics/index.html.erb
<h1>All Topics</h1>

<% @topics.each do |topic| %>
  <%= link_to topic.name, topic_path(topic) %><br>
<% end %>

app/views/topics/show.html.erb
All Current Meetups for <%= @topic.name %>:<br><br>

<% @meetups.each do |meetup| %>
  <%= link_to meetup.event.name, event_path(meetup.id) %><br>
<% end %>